const cols = (...pairs) => pairs.map(([prop, label]) => ({ prop, label }))

export const sheets = {
  'track-buy': {
    title: '采购与原料进厂',
    block: '全程可视化追踪',
    purpose: '进口铁矿走辽港营口三公司，煤炭走营口二公司，国内矿到鞍山基地。港方未对接的节点标待接口，不编造轨迹。',
    rule: '净重以计量为准。原料与成品过磅分开看。回程车不计入入库量。',
    tableTitle: '原料在途与接收',
    columns: cols(
      ['source', '来源'],
      ['ref', '船次/车次'],
      ['goods', '矿种/煤种'],
      ['plan', '计划量(吨)'],
      ['status', '状态'],
      ['eta', '预计入厂'],
      ['yard', '料场'],
    ),
    rows: [
      { source: '辽港营口三公司', ref: '航次 YK3-0918', goods: '进口铁矿', plan: 8200, status: '在途', eta: '09-20 06:00', yard: '待指' },
      { source: '辽港营口二公司', ref: '航次 YK2-0916', goods: '煤炭', plan: 5400, status: '待接口（港方台账）', eta: '09-19 18:00', yard: '煤场1' },
      { source: '国内矿点', ref: '列 D-0918-03', goods: '国内矿', plan: 2100, status: '已过磅待入场', eta: '09-18 11:20', yard: '矿场2' },
      { source: '辽港营口三公司', ref: '辽B·矿3321', goods: '进口铁矿（疏港）', plan: 35, status: '回程，不计入入库', eta: '—', yard: '—' },
    ],
  },
  'track-wip': {
    title: '生产排期与在制',
    block: '全程可视化追踪',
    purpose: '只读排产和工序。物流不在这里改生产计划。热轧卷冷却未完成不能当可装车。试点先接一条冷轧、一条热轧。',
    rule: '排产以产销一体化和 MES 为准。未关联合同的批次不能默认可发运。停产线材线不参与预测。',
    tableTitle: '炉次与冷却',
    columns: cols(
      ['contract', '合同'],
      ['line', '产线'],
      ['heat', '炉次'],
      ['mat', '材料号'],
      ['step', '当前工序'],
      ['cool', '冷却'],
      ['quality', '质量'],
      ['cover', '接入'],
    ),
    rows: [
      { contract: 'HT-250918-01', line: '热轧（试点）', heat: 'H6914', mat: 'R260918001', step: '卷取完成', cool: '剩余 6 小时', quality: '待判', cover: '已接入' },
      { contract: 'HT-250910-22', line: '冷轧（试点）', heat: 'C2201', mat: 'C260910088', step: '轧制中', cool: '不适用', quality: '未判定', cover: '已接入' },
      { contract: '未关联', line: '硅钢', heat: 'S1180', mat: 'S260918014', step: '待排', cool: '—', quality: '—', cover: '未接入，不计零产量' },
      { contract: '—', line: '线材2', heat: '—', mat: '—', step: '停产', cool: '—', quality: '—', cover: '不参与运力' },
    ],
  },
  'track-stock': {
    title: '半成品与成品库存',
    block: '全程可视化追踪',
    purpose: '按库、位、层找到件。账面吨数和现在能吊出来的吨数分开。不同收货单位的板可能垛在一起。',
    rule: '可发量 = 账面 − 积压不可及 − 质量/合同拦截 − 冷却未完成 − 已被运单占用。冷轧坐标未进系统的标纸质盘点。',
    tableTitle: '库存与可发',
    columns: cols(
      ['wh', '库'],
      ['loc', '库位/堆层'],
      ['mat', '材料号'],
      ['goods', '品名'],
      ['book', '账面(吨)'],
      ['block', '不可发'],
      ['ready', '可发'],
      ['why', '原因'],
    ),
    rows: [
      { wh: 'H12热轧', loc: 'A-12 / 第2层', mat: 'R260915018', goods: '热轧卷', book: 28, block: 0, ready: 28, why: '可吊' },
      { wh: '厚板综合库', loc: 'B-03 / 底层', mat: 'H6914007', goods: '中厚板', book: 16, block: 16, ready: 0, why: '上层为其他客户，暂不可吊' },
      { wh: '冷轧成品库', loc: '坐标待补', mat: 'C260914007', goods: '冷轧卷', book: 24, block: 24, ready: 0, why: '纸质巡库，坐标未转入' },
      { wh: 'H12热轧', loc: 'C-01 / 第1层', mat: 'R260917031', goods: '热轧卷', book: 12, block: 12, ready: 0, why: '冷却未完成，约 200℃' },
    ],
  },
  'track-ship': {
    title: '发运计划对照',
    block: '全程可视化追踪',
    purpose: '销售系统下发计划量，物流安排发运量，过磅后形成实发量。对不上的要有主原因。',
    rule: '计划量只能销售侧改。实发量按计量净重，未过磅不算实发。一张提单多种方式时分段列示。',
    tableTitle: '计划量 / 发运量 / 实发量',
    columns: cols(
      ['bl', '提单号'],
      ['customer', '收货单位'],
      ['goods', '品名'],
      ['mode', '发货方式'],
      ['plan', '计划量'],
      ['arranged', '发运量'],
      ['actual', '实发量'],
      ['why', '主原因'],
    ),
    rows: [
      { bl: '9M052609140897', customer: '东北某制造', goods: '热轧卷板', mode: '汽运-集港', plan: 100, arranged: 86, actual: 32, why: '积压不可及 14 吨' },
      { bl: 'TD-0914-007', customer: '大连某仓储', goods: '冷轧卷板', mode: '汽运-直送', plan: 48, arranged: 0, actual: 0, why: '付款未齐' },
      { bl: 'TD-0916-022', customer: '华东某船厂', goods: '中厚板', mode: '水运', plan: 160, arranged: 0, actual: 0, why: '在制未完成' },
      { bl: 'TD-0913-005', customer: '沈阳某贸易', goods: '线材', mode: '铁运', plan: 60, arranged: 60, actual: 0, why: '等车皮兑现' },
    ],
  },
  'track-waybill': {
    title: '运单执行',
    block: '全程可视化追踪',
    purpose: '汽运（直送、物流园、自提、集港）、铁运、集港后段船运都从派车跟到交接。装车按材料号核对，未核对完不能出门。',
    rule: '作业单号以物流运输系统为准。离厂要有有效磅单。无磅单的厂内倒运不进成品外发链。',
    tableTitle: '运单节点',
    columns: cols(
      ['no', '运单号'],
      ['mode', '方式'],
      ['plate', '车牌/车皮'],
      ['node', '当前节点'],
      ['check', '材料核对'],
      ['weigh', '过磅'],
      ['gate', '门岗'],
    ),
    rows: [
      { no: 'YD-0918-01', mode: '汽运-集港', plate: '辽B·A2036', node: '和平桥门排队', check: '未开始', weigh: '未过磅', gate: '和平桥门 #3' },
      { no: 'YD-0918-02', mode: '汽运-直送', plate: '辽B·D1190', node: '装车中', check: '6/6 已核对', weigh: '待过磅', gate: '已进厂' },
      { no: 'YD-0918-04', mode: '铁运短倒', plate: '辽B·C8812', node: '已离场', check: '已核对', weigh: '净重已回写', gate: '成品库东门' },
      { no: 'TB-内倒-11', mode: '场内台班', plate: '厂内 08', node: '厂内', check: '—', weigh: '无外发磅单', gate: '不进外发链' },
    ],
  },
  'track-settle': {
    title: '成本线上管理',
    block: '全程可视化追踪',
    purpose: '物流费用回到合同和订单，线上结算，替代人工对账。正式页面在成本线上管理。',
    rule: '费率未配置只出待计价，不估一个假金额。净重争议以计量为准。二层物流签收节点可以是渠道库。',
    tableTitle: '签收与费项',
    columns: cols(
      ['no', '运单'],
      ['sign', '签收节点'],
      ['qty', '实发/签收'],
      ['fee', '费项'],
      ['amount', '金额'],
      ['status', '状态'],
    ),
    rows: [
      { no: 'YD-0917-08', sign: '客户签收', qty: '32.4 / 32.4', fee: '汽运运费', amount: '待计价', status: '费率未配置' },
      { no: 'YD-0917-02', sign: '码头收货', qty: '86 / 86', fee: '港杂', amount: '已归集', status: '待对账' },
      { no: 'YD-0916-19', sign: '铁路交出', qty: '58.2 / —', fee: '铁运运费', amount: '—', status: '未签收，不可结算' },
      { no: '无运单', sign: '—', qty: '—', fee: '等候费', amount: '—', status: '禁止归集' },
    ],
  },
  'cockpit-yard': {
    title: '基地与库区建模',
    block: '物流驾驶舱',
    purpose: '先把库号、门、磅、装卸点、铁路分区挂上，库号必须和 MES 一致。第一期用平面关系，不承诺三维已上线。',
    rule: '未发布的模型不影响单据。停用库保留历史库号。',
    tableTitle: '库区与通道',
    columns: cols(
      ['base', '基地'],
      ['name', '对象'],
      ['kind', '类型'],
      ['code', '库号/代码'],
      ['model', '模型'],
      ['status', '状态'],
    ),
    rows: [
      { base: '鞍山', name: 'H12热轧库', kind: '成品库', code: 'H12', model: '平面示意', status: '已发布' },
      { base: '鞍山', name: '冷轧成品库', kind: '成品库', code: 'CR-01', model: '坐标待补', status: '试点' },
      { base: '鞍山', name: '和平桥门', kind: '门岗', code: 'GATE-HP', model: '已标注', status: '已发布' },
      { base: '营口', name: '自有港泊位', kind: '港口', code: 'YK-OWN', model: '节点', status: '未三维' },
    ],
  },
  'cockpit-stock': {
    title: '库存动态孪生',
    block: '物流驾驶舱',
    purpose: '占用率低不等于好发。展示来自库存菜单，不另维护一套库存。',
    rule: '没有额定库容的库只显示绝对吨数。纸质盘点库标注非实时。',
    tableTitle: '库容与可发',
    columns: cols(
      ['wh', '库'],
      ['cap', '库容参照'],
      ['occ', '占用'],
      ['ready', '可发占比'],
      ['block', '积压占比'],
      ['live', '时点'],
    ),
    rows: [
      { wh: 'H12热轧', cap: '约 9 万吨', occ: '30%–40%', ready: '账面高、可发被冷却和混垛卡住', block: '有积压', live: '实时账' },
      { wh: '冷轧成品库', cap: '约 2 万吨', occ: '60%–70%', ready: '低于账面', block: '混垛', live: '纸质盘点，非实时' },
      { wh: '厚板综合库', cap: '未配置额定', occ: '按吨展示', ready: '—', block: '跨客户压垛', live: '作业单库位' },
    ],
  },
  'cockpit-port': {
    title: '在途与港口孪生',
    block: '物流驾驶舱',
    purpose: '厂、路、港、船放在一起看衔接。鞍钢营口港务和辽港必须分开，没有坐标就显示节点，不在地图上编位置。',
    rule: '辽港未对接字段留空。轨迹中断不算正常在途。',
    tableTitle: '在途汇合',
    columns: cols(
      ['chain', '链路'],
      ['obj', '对象'],
      ['node', '节点'],
      ['port', '港口主体'],
      ['gap', '断点'],
    ),
    rows: [
      { chain: '原料进厂', obj: '航次 YK3-0918', node: '离港在途', port: '辽港三公司', gap: '无坐标，仅节点' },
      { chain: '成品外发', obj: '辽B·A2036', node: '厂门排队', port: '去自有港集港', gap: '未离厂' },
      { chain: '船运', obj: '锦泰远盛 / A260911013', node: '靠泊作业', port: '鞍钢营口港务', gap: '无' },
      { chain: '船运', obj: '外租轮 08', node: '锚地待泊', port: '自有港', gap: '船等货' },
    ],
  },
  'cockpit-truck': {
    title: '汽运物流视图',
    block: '物流驾驶舱',
    purpose: '看车在门外、厂内、装卸点还是已离厂。自有、长期、临时、自提分开，自提不算运力池。',
    rule: '无定位时位置取最后业务节点。派车动作在车辆智能调度，不在本视图确认。',
    tableTitle: '车辆分布',
    columns: cols(
      ['plate', '车牌'],
      ['kind', '车辆性质'],
      ['status', '状态'],
      ['place', '位置'],
      ['wait', '已等待'],
    ),
    rows: [
      { plate: '辽B·A2036', kind: '自有', status: '门口排队', place: '和平桥门', wait: '28 分' },
      { plate: '辽B·D1190', kind: '长期', status: '装车中', place: '冷轧装车坪', wait: '0' },
      { plate: '客户自提 19', kind: '自提', status: '过磅', place: '磅房2', wait: '不进运力池' },
      { plate: '临时未确认', kind: '临时', status: '未到厂', place: '次日预约', wait: '不可排进当天' },
    ],
  },
  'cockpit-sea': {
    title: '集港与船运视图',
    block: '物流驾驶舱',
    purpose: '一条船看计划集港、已离厂未到港、已到港未装船、已装船。未挂航次的去港车辆单独列出。',
    rule: '直装不进堆场库存，单独一列，避免和堆场重复计算。',
    tableTitle: '航次四段',
    columns: cols(
      ['voyage', '航次'],
      ['ship', '船名'],
      ['plan', '计划集港'],
      ['left', '已离厂未到港'],
      ['yard', '已到港未装'],
      ['loaded', '已装船'],
      ['direct', '直装'],
      ['loose', '未挂船'],
    ),
    rows: [
      { voyage: 'A260911013', ship: '锦泰远盛', plan: '5499 吨', left: '32 吨', yard: '1289 吨', loaded: '进行中', direct: '可直装窗口 07:00-14:00', loose: '0' },
      { voyage: '未挂', ship: '—', plan: '—', left: '辽B·E2201', yard: '—', loaded: '—', direct: '—', loose: '1 车' },
    ],
  },
  'cockpit-rail': {
    title: '铁运物流视图',
    block: '物流驾驶舱',
    purpose: '按 9 个铁路调度分区看请车、兑现、配货、装车、交出。这里不操作调车。',
    rule: '车皮号以铁路系统为准。请车未兑现不能显示成已装车。',
    tableTitle: '分区进度',
    columns: cols(
      ['zone', '分区'],
      ['ask', '请车'],
      ['got', '兑现'],
      ['pick', '已配货'],
      ['load', '已装'],
      ['hand', '已交出'],
    ),
    rows: [
      { zone: '分区3 · 沈阳方向', ask: 4, got: 2, pick: 2, load: 1, hand: 0 },
      { zone: '分区1', ask: 2, got: 0, pick: 0, load: 0, hand: 0 },
      { zone: '分区7', ask: 1, got: 1, pick: 0, load: 0, hand: 0 },
    ],
  },
  'forecast-cap': {
    title: '按生产排单预测运力',
    block: '产品准发预测',
    purpose: '货还没入库时，按排产和地区估算车次或车皮。长江以南倾向集港船运，长江以北走汽运或铁运。结果是建议，不自动下单。',
    rule: '只预测已关联合同的排产。热轧可装车日要加上约 24 小时冷却。非试点产线标低可信。',
    tableTitle: '未来入库与建议运力',
    columns: cols(
      ['day', '日期'],
      ['line', '产线'],
      ['goods', '品名'],
      ['inTon', '预计入库'],
      ['readyDay', '可装车日'],
      ['area', '客户地区'],
      ['mode', '建议方式'],
      ['need', '建议运力'],
      ['trust', '可信'],
    ),
    rows: [
      { day: '09-19', line: '热轧试点', goods: '热轧卷', inTon: 420, readyDay: '09-20', area: '营口集港', mode: '汽运集港', need: '半挂 12 车', trust: '高' },
      { day: '09-20', line: '冷轧试点', goods: '冷轧卷', inTon: 180, readyDay: '09-20', area: '大连', mode: '汽运直送', need: '半挂 6 车', trust: '高' },
      { day: '09-21', line: '线材', goods: '线材', inTon: 260, readyDay: '09-21', area: '沈阳', mode: '铁运', need: '车皮 4', trust: '中' },
      { day: '09-22', line: '硅钢', goods: '硅钢片', inTon: 90, readyDay: '—', area: '华东', mode: '不自动建议', need: '—', trust: '低，未接入' },
    ],
  },
  'forecast-time': {
    title: '准发时间预测',
    block: '产品准发预测',
    purpose: '给出预计哪一班能准发，并标明把握。这是预测不是承诺。已可准发的不再给一个未来时点。',
    rule: '缺质检周期或倒垛工时时，把握最高只能是中。插单改变生产顺序后重算并保留上一版。',
    tableTitle: '预计准发时点',
    columns: cols(
      ['order', '订单'],
      ['goods', '品名'],
      ['time', '预计准发'],
      ['prev', '上一版'],
      ['level', '把握'],
      ['reason', '依据'],
    ),
    rows: [
      { order: 'SO-20260915018', goods: '热轧卷板', time: '当前可发', prev: '09-18 08:00', level: '高', reason: '质量合格、合同生效、可吊 86 吨' },
      { order: 'SO-20260914007', goods: '冷轧卷板', time: '09-18 16:00', prev: '09-18 10:00', level: '中', reason: '混垛压住，倒垛工时未采集' },
      { order: 'SO-20260916022', goods: '中厚板', time: '09-20 10:00', prev: '—', level: '低', reason: '在制未完成且质量未判' },
      { order: 'SO-20260917031', goods: '热轧卷板', time: '无法给出承诺', prev: '09-22 14:00', level: '低', reason: '合同评审中，预测作废重算' },
    ],
  },
  'dispatch-pressure': {
    title: '库存压力分级',
    block: '车辆智能调度',
    purpose: '按可发占比、积压、预计入库和装卸等待给库分级。高压库的已准发订单优先要车。分级不自动派车。',
    rule: '库容未维护的不判高压。原因要能看懂：可发低可能是混垛，不是没货。',
    tableTitle: '库压力',
    columns: cols(
      ['wh', '库'],
      ['level', '等级'],
      ['why', '原因'],
      ['action', '对派车的影响'],
    ),
    rows: [
      { wh: '冷轧成品库', level: '高压', why: '占用 60%–70%，且混垛导致可发低于账面', action: '已准发冷卷优先匹配车辆' },
      { wh: 'H12热轧', level: '关注', why: '占用不高，但月末入库历史上明显升高', action: '三天窗口预留半挂' },
      { wh: '厚板综合库', level: '未分级', why: '未维护额定库容', action: '不参与高压排序' },
    ],
  },
  'outbound-split': {
    title: '汽运与铁运动态匹配',
    block: '出厂计划智能编制',
    purpose: '一张提单可以拆成汽运吨和铁运吨。任一侧失败要回到这一行改，不能两边同时占着同一批货。',
    rule: '合计不得超过可发量和计划量。铁运未请车成功前，不自动把吨位改派汽运。',
    tableTitle: '汽铁拆分',
    columns: cols(
      ['bl', '提单'],
      ['ready', '可发'],
      ['truck', '汽运吨'],
      ['rail', '铁运吨'],
      ['truckSt', '汽运任务'],
      ['railSt', '车皮'],
      ['next', '下一步'],
    ),
    rows: [
      { bl: 'TD-0913-005 线材', ready: 60, truck: 0, rail: 60, truckSt: '未生成', railSt: '请车 2 / 兑现 0', next: '等兑现，不自动改汽运' },
      { bl: 'TD-0918-11 热卷', ready: 86, truck: 54, rail: 32, truckSt: '已下发 2 车', railSt: '兑现 1 车皮', next: '铁运剩余 待计划员确认是否改汽运' },
      { bl: 'TD-0916-022 中板', ready: 0, truck: 0, rail: 0, truckSt: '—', railSt: '—', next: '可发为 0，不能拆' },
    ],
  },
  'terminal-window': {
    title: '集港衔接',
    block: '码头智能调度',
    purpose: '出厂计划引用码头确认的集港窗口。没有确认窗口的船，不能标成已对齐船期。',
    rule: '窗口变更要通知已派车辆。堆场占用只在港方给了能力数时才判断够不够。',
    tableTitle: '集港窗口',
    columns: cols(
      ['ship', '船名'],
      ['window', '窗口'],
      ['confirm', '是否确认'],
      ['risk', '窗口内未发'],
      ['yard', '堆场'],
    ),
    rows: [
      { ship: '锦泰远盛', window: '09-18 07:00–14:00', confirm: '已确认', risk: '热卷 32 吨仍在厂门', yard: '占用 72%' },
      { ship: '鞍钢海运03', window: '集港提前 24 小时', confirm: '待码头确认', risk: '中厚板尚未准发', yard: '占用 41%' },
      { ship: '外租轮 08', window: '截关 09-19 08:00', confirm: '已确认', risk: '集港仅 10%，船等货', yard: '占用 63%' },
    ],
  },
  'terminal-direct': {
    title: '车船直装',
    block: '码头智能调度',
    purpose: '船在直装窗口、货能按时送到、不需要先改配，才生成直装运单。直装失败转集港进场，不能停在中间。',
    rule: '直装不计入堆场库存。成品库发不出时，优先直装已准发且交期最紧的分批。比例用于跟踪，不把 14% 写死成考核初值。',
    tableTitle: '直装条件',
    columns: cols(
      ['batch', '装船分批'],
      ['goods', '品名'],
      ['check', '条件'],
      ['result', '结论'],
      ['reason', '原因'],
    ),
    rows: [
      { batch: '007', goods: '热轧卷板', check: '船靠泊且可发', result: '可直装', reason: '建议到港 07:00-14:00' },
      { batch: '014', goods: '冷轧薄板', check: '成品库可发不足', result: '不直装', reason: '库容限制，转堆场' },
      { batch: '005', goods: '硅钢片', check: '船在锚地', result: '条件不足', reason: '船等货，先不派直装' },
    ],
  },
  'loading-merge': {
    title: '铁运拼单',
    block: '车辆智能配载',
    purpose: '同到站、允许混装的已准发订单合成车皮，提高标重利用率。不在这里算全程运费。',
    rule: '客户禁止拼装的不进入建议。质量未放行不能预占车皮。兑现车皮不够时按发运优先级砍单。',
    tableTitle: '拼单建议',
    columns: cols(
      ['to', '到站'],
      ['wagon', '车皮'],
      ['orders', '订单'],
      ['weight', '已配/标重'],
      ['mix', '混装'],
      ['status', '状态'],
    ),
    rows: [
      { to: '沈阳', wagon: 'C70-8821', orders: 'SO-13005 线材', weight: '58.2 / 70', mix: '单品类', status: '请车兑现中' },
      { to: '沈阳', wagon: '待兑现', orders: 'SO-13005 剩余 + SO-13011', weight: '— / 70', mix: '允许', status: '建议，未确认' },
      { to: '天津', wagon: '—', orders: '客户指定不拼', weight: '—', mix: '禁止', status: '不进入建议' },
    ],
  },
  'loading-stow': {
    title: '铁运配载与库位',
    block: '车辆智能配载',
    purpose: '先看件在哪一层，再决定装进哪节车皮。没有堆层就不给库位建议。算法仍是规则建议，模型清单尚未确认。',
    rule: '实际件号与方案不一致时以实际回写。被压住的件要生成倒垛，否则纸面满载、现场吊不出。',
    tableTitle: '车皮件号与垛位',
    columns: cols(
      ['wagon', '车皮'],
      ['mat', '材料号'],
      ['loc', '库位/层'],
      ['above', '上层压件'],
      ['advice', '建议'],
    ),
    rows: [
      { wagon: 'C70-8821', mat: 'L260913005-01', loc: '线材库 2-1 / 顶层', above: '无', advice: '可直接吊' },
      { wagon: 'C70-8821', mat: 'L260913005-08', loc: '线材库 2-4 / 底层', above: '其他合同 2 件', advice: '先倒垛，暂不可发' },
      { wagon: '待配', mat: '冷轧库卷', loc: '无堆层', above: '—', advice: '先盘点，不给建议' },
    ],
  },
  'support-api': {
    title: '接口集成',
    block: '基础支撑',
    purpose: '管要接哪些系统、字段和失败补传。未调研的不能标已通。失败后界面不能仍显示已同步。',
    rule: '重传按业务主键幂等，不能生成第二张运单。烽火台只留名称。',
    tableTitle: '接口台账',
    columns: cols(
      ['sys', '系统'],
      ['owner', '归属'],
      ['mode', '方式'],
      ['status', '状态'],
      ['note', '说明'],
    ),
    rows: [
      { sys: '销售物流系统', owner: '鞍信', mode: '待定 Rest/MQ', status: '联调前', note: '读计划量，回写不能发运原因' },
      { sys: '物流运输系统', owner: '鞍信', mode: '待定', status: '联调前', note: '作业单号以其为准' },
      { sys: '德邻汽运', owner: '德邻陆港', mode: '待定', status: '未通', note: '未通前允许手工登记并标来源' },
      { sys: '计量 / 门禁', owner: '鞍钢自有', mode: '待定', status: '待接', note: '净重、抬杆' },
      { sys: '智慧码头 / 数据湖', owner: '码头 / 数科', mode: '待定', status: '预期 12 月船期', note: '此前船期人工' },
      { sys: '烽火台', owner: '待核对', mode: '—', status: '未调研', note: '不作为数据来源' },
    ],
  },
  'support-lake': {
    title: '数据中台',
    block: '基础支撑',
    purpose: '订单、材料、库存、运单、船舶、费用要有主题和主键。本系统不另存一套第二库存。',
    rule: '代码对照未发布时显示原系统代码，不自行翻译。',
    tableTitle: '主题与对照',
    columns: cols(
      ['theme', '主题'],
      ['key', '主键'],
      ['source', '来源'],
      ['map', '对照'],
    ),
    rows: [
      { theme: '订单材料', key: '订单号 / 材料号', source: '产销、MES', map: '跨厂编号是否连续：待确认' },
      { theme: '库存', key: '库号+库位+材料号', source: 'MES / 物流库', map: '库号必须一致' },
      { theme: '运单', key: '作业单号', source: '物流运输系统', map: '不另编对外单号' },
      { theme: '船舶', key: '航次号', source: '智慧码头', map: '自有港与辽港分开' },
    ],
  },
  'support-iot': {
    title: '物联感知',
    block: '基础支撑',
    purpose: '第一期以门禁、过磅、冷轧坐标为主。热卷芯片耐温未验证，试验数据不参与可发量。',
    rule: '正式采集点中断时，单据回到人工节点。',
    tableTitle: '采集点',
    columns: cols(
      ['point', '采集点'],
      ['place', '位置'],
      ['use', '是否参与业务'],
      ['status', '状态'],
    ),
    rows: [
      { point: '门禁抬杆', place: '和平桥门', use: '参与排队', status: '待接' },
      { point: '汽车衡', place: '磅房', use: '参与净重', status: '待接' },
      { point: '冷轧坐标', place: '冷轧库', use: '可补录', status: '纸质为主' },
      { point: '热卷芯片', place: '热轧发运', use: '不参与可发量', status: '试验，耐温未定' },
    ],
  },
  'support-twin': {
    title: '数字孪生',
    block: '基础支撑',
    purpose: '管理场景版本和数据绑定。推演结果默认不回写出厂计划，采纳必须人工确认。',
    rule: '模型和实库不符时以库存单据为准。',
    tableTitle: '场景版本',
    columns: cols(
      ['ver', '版本'],
      ['cover', '覆盖'],
      ['bind', '绑定'],
      ['sim', '推演'],
    ),
    rows: [
      { ver: 'v0.1 平面', cover: 'H12、和平桥门、冷轧库', bind: '库号已对照', sim: '未运行' },
      { ver: '三维', cover: '未建', bind: '—', sim: '第一期不承诺' },
    ],
  },
  'support-algo': {
    title: '算法与模型',
    block: '基础支撑',
    purpose: '准发时间、运力匹配、库位推荐、满载率、汽铁拆分都要登记状态。待确认的只能当参考，不能自动派车。',
    rule: '输入缺失时返回无法计算，不给一个数。',
    tableTitle: '建议算法',
    columns: cols(
      ['name', '名称'],
      ['type', '类型'],
      ['status', '状态'],
      ['scope', '范围'],
    ),
    rows: [
      { name: '准发时间', type: '规则 + 时间序列（未确认）', status: '参考', scope: '试点产线' },
      { name: '汽运车型运量匹配', type: '规则', status: '待确认', scope: '不可自动下发' },
      { name: '库位推荐', type: '规则', status: '待确认', scope: '无堆层则不计算' },
      { name: '装车满载率', type: '规则', status: '待确认', scope: '只展示，不考核' },
    ],
  },
  'support-screen': {
    title: '大屏可视化',
    block: '基础支撑',
    purpose: '大屏只绑定驾驶舱已发布的指标，不另做一套数。大屏不完成派车确认。',
    rule: '刷新失败要显示最后成功时间，不能把旧画面当实时。',
    tableTitle: '屏幕',
    columns: cols(
      ['screen', '屏幕'],
      ['widgets', '组件'],
      ['refresh', '刷新'],
      ['status', '状态'],
    ),
    rows: [
      { screen: '调度室主屏', widgets: '排队、装卸等待、船等货、可发占比', refresh: '1 分钟', status: '未发布' },
      { screen: '会议室', widgets: '同主屏，只读', refresh: '5 分钟', status: '草案' },
    ],
  },
  'infra-wh': {
    title: '制造库规模',
    block: '基础设施',
    purpose: '在用库约 148 个。第一期不承诺全部上线。未接入库的货显示库未接入，不能当成库存为零。',
    rule: '停用库不能被新作业单选择。库号与 MES 不一致时先对照。',
    tableTitle: '库房接入',
    columns: cols(
      ['code', '库'],
      ['stage', '阶段'],
      ['note', '说明'],
    ),
    rows: [
      { code: 'H12 热轧', stage: '试点', note: '库容约 9 万吨，占用约 30%–40%' },
      { code: '冷轧成品库', stage: '试点', note: '约 2 万吨，高约 50 米，纸质巡库' },
      { code: '厚板综合库 / 4300 / 2500', stage: '对照中', note: '作业单已有库位堆层' },
      { code: '其余制造库', stage: '未接入', note: '名录待导入，约 148 个在用' },
    ],
  },
  'infra-line': {
    title: '钢材产线',
    block: '基础设施',
    purpose: '按调研维护产线并标试点、停产。非试点不参与自动预测，停产不产生运力需求。',
    rule: '图上 20 条是规划输入，清单以核对后的主数据为准。',
    tableTitle: '产线',
    columns: cols(
      ['name', '产线'],
      ['count', '条数'],
      ['flag', '标记'],
    ),
    rows: [
      { name: '冷轧', count: '4', flag: '试点 1 条' },
      { name: '镀锌 / 彩涂 / 鞍神高强', count: '2 / 1 / 1', flag: '未接入' },
      { name: '硅钢', count: '2', flag: '未接入' },
      { name: '热轧（卷 3 + 切板 1）', count: '4', flag: '试点 1 条' },
      { name: '大型（轨梁、连轧、无缝）', count: '3', flag: '未接入' },
      { name: '线材', count: '2', flag: '其中 1 条停产' },
      { name: '原板', count: '1', flag: '未接入' },
    ],
  },
  'infra-weigh': {
    title: '过磅能力',
    block: '基础设施',
    purpose: '日均过磅 2000 辆以上。成品计划下发前要能看到磅房是否排满。本页不控制磅秤。',
    rule: '作废磅单不计入完成量。磅故障期间运单走人工磅单。',
    tableTitle: '磅房负荷（示意）',
    columns: cols(
      ['scale', '磅房'],
      ['done', '今日有效磅单'],
      ['queue', '排队'],
      ['mix', '业务'],
    ),
    rows: [
      { scale: '磅房1', done: '原料为主', queue: '12', mix: '原料 / 成品分开统计' },
      { scale: '磅房2', done: '成品外发', queue: '7', mix: '成品' },
      { scale: '合计参照', done: '日均 2000+', queue: '—', mix: '含厂内与外发，外发单列' },
    ],
  },
  'infra-rail': {
    title: '铁路调度分区',
    block: '基础设施',
    purpose: '9 个分区及货场代码对照。未对照的车皮可以查，但不能自动预指货场。',
    rule: '分区边界以铁路部门为准。',
    tableTitle: '分区对照',
    columns: cols(
      ['zone', '分区'],
      ['yard', '货场'],
      ['code', '铁路代码'],
      ['status', '对照'],
    ),
    rows: [
      { zone: '分区1', yard: '待现场确认', code: '—', status: '未对照' },
      { zone: '分区3', yard: '线材货场', code: '待对照', status: '可查询，不可自动预指' },
      { zone: '其余至分区9', yard: '待导入', code: '—', status: '名录未齐' },
    ],
  },
  'infra-paper': {
    title: '人工纸质作业',
    block: '基础设施',
    purpose: '冷轧巡库、部分装车、码头排班仍可能是纸单。补录默认不参与自动派车，复核后才生效。',
    rule: '已有接口数据的业务禁止再补一张有效纸单。补录错误只作废，不物理删除。',
    tableTitle: '纸单',
    columns: cols(
      ['type', '类型'],
      ['source', '来源'],
      ['status', '状态'],
      ['auto', '自动派车'],
    ),
    rows: [
      { type: '冷轧巡库', source: '纸质补录', status: '待复核', auto: '否' },
      { type: '早晨发运统计', source: '原微信群', status: '被出厂计划替代', auto: '否' },
      { type: '码头排班', source: '港方纸单', status: '待数字化', auto: '否' },
    ],
  },
  'infra-net': {
    title: '网络与传感器',
    block: '基础设施',
    purpose: '库区网络不稳定时允许离线核对，恢复后再上传。延迟期间禁止自动确认离厂和自动改库存。',
    rule: '长期无网络的点走纸单，不反复刷屏，改为每日汇总。',
    tableTitle: '延迟',
    columns: cols(
      ['place', '位置'],
      ['lag', '数据时点'],
      ['limit', '限制'],
    ),
    rows: [
      { place: '冷轧库', lag: '昨日盘点', limit: '不自动改可发量' },
      { place: '和平桥门', lag: '待接门禁', limit: '队列可标为手工' },
      { place: '自有码头', lag: '船期人工', limit: '不把人工台账显示成接口实时' },
    ],
  },
  'sys-lts': {
    title: '物流运输系统',
    block: '关联系统',
    purpose: '覆盖制造物流、场内物流（台班/单任务）、采购物流和成品作业单。本平台下发计划和确认，不并行再编一套作业单号。',
    rule: '场内倒运默认不进成品可视链。电商运输平台是否纳入待确认。',
    tableTitle: '读写边界',
    columns: cols(
      ['item', '数据'],
      ['rw', '方向'],
      ['note', '约定'],
    ),
    rows: [
      { item: '成品/厚板/原板作业单', rw: '读', note: '单号以其为准' },
      { item: '铁路车号匹配、预指货场', rw: '读', note: '失败不能显示为已对上' },
      { item: '出厂计划确认结果', rw: '写', note: '接口未通前导出任务单' },
      { item: '采购回运、料场', rw: '读', note: '进入原料进厂菜单' },
    ],
  },
  'sys-sales': {
    title: '销售物流系统',
    block: '关联系统',
    purpose: '即销售管理系统。它下发计划量。本平台只消费准发和提单，不替代 L3 做标签和拣货。',
    rule: '物流只能回写兑现量和不能发的原因，不能改计划量。',
    tableTitle: '读取范围',
    columns: cols(
      ['item', '数据'],
      ['rw', '方向'],
      ['note', '约定'],
    ),
    rows: [
      { item: '发运计划 / 提单 / 发货方式', rw: '读', note: '计划量' },
      { item: '合同生效、结算客户', rw: '读', note: '未生效不可准发' },
      { item: '不能发运原因', rw: '写', note: '积压、无运力、无船期等' },
      { item: '二层渠道配送单', rw: '可不读', note: '二层目前较弱' },
    ],
  },
  'sys-3pl': {
    title: '3PL系统',
    block: '关联系统',
    purpose: '德邻使用的协同平台，回传实运、仓储和结算。调度指令和运力池若在德邻调度，要和 3PL 划开。',
    rule: '回传不能覆盖厂内过磅净重。未上线字段标待调研。',
    tableTitle: '回传',
    columns: cols(
      ['item', '数据'],
      ['from', '来自'],
      ['note', '约定'],
    ),
    rows: [
      { item: '车辆执行、装卸时间', from: '3PL / 德邻', note: '写入运单节点' },
      { item: '运力池、派车', from: '德邻调度', note: '与 3PL 结算回传分开' },
      { item: '费用', from: '3PL', note: '进入费用归集，费率未定则待计价' },
      { item: '微信派车结果', from: '人工', note: '接口未通时的过渡，不是 3PL 数据' },
    ],
  },
  'sys-beacon': {
    title: '烽火台系统',
    block: '关联系统',
    purpose: '现有材料没有展开这个系统。确认前，驾驶舱和调度都不出现来自烽火台的数。',
    rule: '未确认不得作为数据来源。若名称已变或不是物流系统，从范围删除并留记录。',
    tableTitle: '待核对',
    columns: cols(
      ['item', '待确认'],
      ['status', '状态'],
      ['note', '说明'],
    ),
    rows: [
      { item: '谁在用、管定位还是报警', status: '未调研', note: '不编造功能' },
      { item: '是否与德邻调度重复', status: '未调研', note: '重复则不重复对接' },
      { item: '有没有接口', status: '未调研', note: '没有接口就不进台账已通' },
    ],
  },
  'sys-train': {
    title: '列车调度系统',
    block: '关联系统',
    purpose: '和铁运 ERP、现车一起提供车皮状态。本平台不改列调信号和连锁。',
    rule: '车皮号以铁路系统为准。老 ERP 已替换的不再对接。',
    tableTitle: '读取',
    columns: cols(
      ['item', '数据'],
      ['from', '来自'],
      ['note', '约定'],
    ),
    rows: [
      { item: '请车兑现、到发、货场', from: '列调 / 铁运 ERP', note: '驱动铁运视图' },
      { item: '现车、车皮号', from: '现车系统', note: '第一期只对号' },
      { item: '连锁信号', from: 'VC', note: '不在物流界面操作' },
      { item: '配载需求', from: '本平台', note: '是否回写铁路系统待确认' },
    ],
  },
  'sys-port': {
    title: '智慧码头系统',
    block: '关联系统',
    purpose: '当前能提取装船清单。装载方案和排班仍多靠人工。12 月船期预期从数据湖来，延期则继续人工台账。',
    rule: '港方已出库和厂内实发不一致时并列展示，不互相覆盖。辽港系统不放在这一条里。',
    tableTitle: '对接',
    columns: cols(
      ['item', '数据'],
      ['rw', '方向'],
      ['note', '约定'],
    ),
    rows: [
      { item: '装船清单、航次、已出库', rw: '读', note: '提单、分批、件数重量' },
      { item: '船期 ETA', rw: '读或人工', note: '数据湖未通前人工，来源要标明' },
      { item: '二级配载、作业流水', rw: '只读或外链', note: '不在本平台复制码头界面' },
      { item: '直装结果', rw: '回写待定', note: '双方都要能看见直装标记' },
    ],
  },
}
