/** ②～⑦ 业务原型数据（调研梳理） */

export const bizModuleState = {
  forecastMeta: {
    goal: '综合销售计划量、质量判定、库存与积压可及性，预判可准发量与准发时点（账面库存≠可发量）。',
    conditions: ['质量判定合格', '合同生效', '交期窗口内', '积压可及（未被压住）'],
    note: '销售管理系统下发运计划（计划量）；物流运输系统派车执行。因堆存积压，账面 1000 吨可能仅 800 吨可实际发运。',
    sources: [
      { name: '销售管理系统', owner: '鞍信公司' },
      { name: '物流运输系统', owner: '鞍信公司' },
      { name: '产销一体化系统', owner: '鞍信公司' },
      { name: '制造执行系统（MES）', owner: '鞍钢自有系统' },
      { name: '质量管理系统', owner: '鞍钢自有系统' },
    ],
  },
  forecastList: [
    {
      orderNo: 'SO-20260915018',
      goods: '热轧卷板',
      customer: '东北某制造',
      planQty: 100,
      bookStock: 100,
      blockedQty: 14,
      readyQty: 86,
      shipMode: '汽运-集港',
      quality: '合格',
      contract: '已生效',
      predictTime: '09-18 08:00',
      confidence: '高',
      blockReason: '底层积压 14t 暂不可吊',
      status: '可准发',
    },
    {
      orderNo: 'SO-20260914007',
      goods: '冷轧卷板',
      customer: '大连某仓储',
      planQty: 48,
      bookStock: 48,
      blockedQty: 24,
      readyQty: 24,
      shipMode: '汽运-直送',
      quality: '合格',
      contract: '已生效',
      predictTime: '09-18 16:00',
      confidence: '中',
      blockReason: '混垛压住 + 付款未齐',
      status: '条件待满足',
    },
    {
      orderNo: 'SO-20260916022',
      goods: '中厚板',
      customer: '华东某船厂',
      planQty: 160,
      bookStock: 40,
      blockedQty: 0,
      readyQty: 0,
      shipMode: '水运-船运南下',
      quality: '未判定',
      contract: '已生效',
      predictTime: '09-20 10:00',
      confidence: '中',
      blockReason: '在制未完成 / 待质检',
      status: '预测中',
    },
    {
      orderNo: 'SO-20260913005',
      goods: '线材',
      customer: '沈阳某贸易',
      planQty: 60,
      bookStock: 60,
      blockedQty: 0,
      readyQty: 60,
      shipMode: '铁运',
      quality: '合格',
      contract: '已生效',
      predictTime: '09-17 18:00',
      confidence: '高',
      blockReason: '—',
      status: '可准发',
    },
    {
      orderNo: 'SO-20260917031',
      goods: '热轧卷板',
      customer: '营口某加工',
      planQty: 40,
      bookStock: 12,
      blockedQty: 12,
      readyQty: 0,
      shipMode: '汽运-物流园',
      quality: '未判定',
      contract: '评审中',
      predictTime: '09-22 14:00',
      confidence: '低',
      blockReason: '计划量有、实物被压且合同未齐',
      status: '不可准发',
    },
  ],

  dispatchMeta: {
    goal: '看清车辆在哪排队、堵在哪个门、哪个装卸点等待最长，并按当天/三天/订单维度做车型运量匹配。',
    sources: [
      { name: '德邻陆港汽运调度系统', owner: '德邻陆港' },
      { name: '运力池管理', owner: '德邻陆港' },
      { name: '物流运输系统', owner: '鞍信公司' },
      { name: '销售管理系统', owner: '鞍信公司' },
    ],
    kpis: [
      { label: '车型错配率', value: '8.6%', tip: '大车拉小货/小车装不下占比' },
      { label: '平均待料等待', value: '46 分', tip: '到厂→开始装车' },
      { label: '空驶率', value: '12%', tip: '空驶里程÷总里程' },
      { label: '准点发运率', value: '91%', tip: '按计划完成装车发运' },
    ],
  },
  capacityPool: [
    { label: '运力池', value: 186, unit: '辆' },
    { label: '空闲', value: 42, unit: '辆' },
    { label: '装卸中', value: 28, unit: '辆' },
    { label: '门口排队', value: 26, unit: '辆' },
  ],
  plantQueues: [
    { gate: '和平桥门', queue: 14, waitMin: 38, peak: '07:30-09:00', stagger: '建议错峰进厂' },
    { gate: '成品库东门', queue: 9, waitMin: 52, peak: '装车回车高峰', stagger: '限制回车占道' },
    { gate: '铁运交接门', queue: 3, waitMin: 18, peak: '车皮到发窗', stagger: '与国铁窗口对齐' },
  ],
  loadPointWaits: [
    { point: '热轧装车坪', bays: 3, queue: 7, waitMin: 58, longest: '最长', machines: '行车×2' },
    { point: '冷轧装车坪', bays: 2, queue: 4, waitMin: 41, bottleneck: '中', machines: '行车+装载机' },
    { point: '线材装车点', bays: 2, queue: 2, waitMin: 22, bottleneck: '低', machines: '行车×1' },
  ],
  vehicleTasks: [
    {
      demandNo: 'YD-0918-01',
      orderNo: 'SO-20260915018',
      goods: '热轧卷 86t',
      route: '厂区 → 鲅鱼圈集港',
      needType: '半挂 35t',
      plate: '辽B·A2036',
      matchScore: 96,
      locate: '和平桥门排队 #3',
      horizon: '当天',
      status: '建议派车',
      waitMin: 28,
    },
    {
      demandNo: 'YD-0918-02',
      orderNo: 'SO-20260914007',
      goods: '冷轧卷 24t',
      route: '厂区 → 客户直送',
      needType: '半挂 35t',
      plate: '辽B·D1190',
      matchScore: 88,
      locate: '冷轧装车坪作业',
      horizon: '当天',
      status: '执行中',
      waitMin: 0,
    },
    {
      demandNo: 'YD-0918-03',
      orderNo: 'SO-20260916022',
      goods: '中厚板 32t',
      route: '中板厂 → 营口港',
      needType: '栏板 20t×2',
      plate: '待匹配',
      matchScore: 0,
      locate: '运力紧张',
      horizon: '三天窗',
      status: '运力紧张',
      waitMin: 95,
    },
    {
      demandNo: 'YD-0918-04',
      orderNo: 'SO-20260913005',
      goods: '线材 31.5t',
      route: '线材库 → 沈阳（铁运衔接短倒）',
      needType: '半挂 35t',
      plate: '辽B·C8812',
      matchScore: 91,
      locate: '已离场',
      horizon: '按订单',
      status: '已完成',
      waitMin: 0,
    },
  ],

  outboundMeta: {
    goal: '厘清多式联运为何如此排、插单如何处理、发运优先级，以及交货日→最晚发运→最晚发车换算。',
    sources: [
      { name: '销售管理系统', owner: '鞍信公司' },
      { name: '物流运输系统', owner: '鞍信公司' },
      { name: '产销一体化系统', owner: '鞍信公司' },
      { name: '德邻陆港汽运调度系统', owner: '德邻陆港' },
    ],
  },
  outboundRules: {
    whyModes: [
      { mode: '汽运直送', why: '长江以北近距客户、交期紧、批次小' },
      { mode: '汽运集港', why: '衔接自有港/辽港船期，覆盖长江以南' },
      { mode: '铁运', why: '客户指定或运费更优，覆盖最远至长江以北' },
      { mode: '水运南下', why: '大批量长距离，船运为主力' },
    ],
    priority: ['客户等级', '交期紧迫度', '船期/车皮窗口', '可准发量是否到位', '运输方式约束'],
    insertOrder: '插单先占运力与装车时段，挤压同优先级低的计划；需同步改派车与装车清单。',
    dateRule: '交货日期 → 倒推在途时效 → 最晚发运日 → 再倒推最晚发车/装车开始时间',
    railShare: '铁运约占外发 28%（原型示意），车皮兑现率约 82%',
  },
  outboundPlans: [
    {
      planNo: 'OB-0918-A1',
      customer: '东北某制造',
      goods: '热轧卷',
      ton: 86,
      deliveryDate: '09-20',
      latestShip: '09-19 18:00',
      latestDepart: '09-19 14:00',
      mode: '汽运-集港',
      priority: '高',
      insert: '否',
      trips: 3,
      sequence: '08:00 / 10:30 / 13:00',
      status: '待确认',
    },
    {
      planNo: 'OB-0918-B2',
      customer: '华东某船厂',
      goods: '中厚板',
      ton: 160,
      deliveryDate: '09-25',
      latestShip: '09-21 12:00',
      latestDepart: '集港 09-20',
      mode: '水运-南下',
      priority: '高',
      insert: '船期插单',
      trips: '船期衔接',
      sequence: '集港提前 24h',
      status: '已变更',
    },
    {
      planNo: 'OB-0918-C1',
      customer: '大连某仓储',
      goods: '冷轧卷',
      ton: 48,
      deliveryDate: '09-19',
      latestShip: '09-19 20:00',
      latestDepart: '09-19 16:00',
      mode: '汽运-直送',
      priority: '中',
      insert: '否',
      trips: 2,
      sequence: '09:00 / 15:00',
      status: '已下发',
    },
    {
      planNo: 'OB-0918-R1',
      customer: '沈阳某贸易',
      goods: '线材',
      ton: 60,
      deliveryDate: '09-22',
      latestShip: '09-21 10:00',
      latestDepart: '请车兑现后',
      mode: '铁运',
      priority: '中',
      insert: '否',
      trips: '车皮 2',
      sequence: '请车→配货→装车',
      status: '编制中',
    },
  ],

  terminalMeta: {
    goal: '码头侧已调研：船舶动态、泊位堆场、集港与车船直装条件；衔接出厂计划与车辆到场时序。',
    surveyed: true,
    sources: [
      { name: '码头系统（营口/鲅鱼圈/双楼）', owner: '码头管理单位' },
      { name: '物流运输系统', owner: '鞍信公司' },
      { name: '德邻陆港汽运调度系统', owner: '德邻陆港' },
    ],
  },
  terminalJobs: [
    {
      terminal: '鲅鱼圈',
      berth: '1#泊位',
      vessel: '鞍钢海运01',
      eta: '09-18 06:00',
      ata: '已靠泊',
      cargo: '热轧卷 280t',
      yardCap: '堆场占用 72%',
      gatherProgress: 68,
      directLoad: '可直装',
      truckWindow: '07:00-14:00',
      status: '作业中',
    },
    {
      terminal: '营口基地',
      berth: '2#泊位',
      vessel: '鞍钢海运03',
      eta: '09-19 10:00',
      ata: '预到港',
      cargo: '中厚板 160t',
      yardCap: '堆场占用 41%',
      gatherProgress: 22,
      directLoad: '需减载',
      truckWindow: '集港提前 24h',
      status: '待集港',
    },
    {
      terminal: '双楼',
      berth: '堆场作业',
      vessel: '—',
      eta: '—',
      ata: '—',
      cargo: '冷轧倒运 / 重进重出评估',
      yardCap: '堆场占用 55%',
      gatherProgress: 40,
      directLoad: '不适用',
      truckWindow: '现场评估中',
      status: '堆场作业',
    },
    {
      terminal: '鲅鱼圈',
      berth: '4#泊位',
      vessel: '外租轮 08',
      eta: '09-18 22:00',
      ata: '锚地待泊',
      cargo: '线材 95t',
      yardCap: '堆场占用 63%',
      gatherProgress: 10,
      directLoad: '条件不足',
      truckWindow: '截关 09-19 08:00',
      status: '船等货',
    },
  ],

  loadingMeta: {
    goal: '同流向、同交期订单合并配载，减少车次。钢卷、盒板一票多车时，先装的车作业，后续车在坪等待。',
    sources: [
      { name: '物流运输系统', owner: '鞍信公司' },
      { name: '列车调度系统', owner: '鞍钢自有系统' },
      { name: '销售管理系统', owner: '鞍信公司' },
    ],
    kpis: [
      { label: '合并后车次', value: '11', tip: '较分单发运少 4 车' },
      { label: '后续车等待', value: '26 分', tip: '钢卷、盒板一票多车' },
      { label: '车皮利用率', value: '83%', tip: '已兑现车皮' },
      { label: '未兑现车皮', value: '2', tip: '不记已配载' },
    ],
  },
  loadingPlans: [
    {
      loadNo: 'LD-1001',
      mode: '汽运',
      carpool: '同流向同交期合并',
      direction: '鲅鱼圈集港',
      date: '09-19',
      orders: 'SO-15018 + SO-15022',
      plate: '辽B·A2036',
      seq: '第 1 车，装车中',
      wait: '0',
      vehicleLimit: '半挂 35t',
      goods: '热轧卷×8',
      mixOk: '同品类可混',
      weight: 32.4,
      fillRate: 91,
      status: '装车中',
    },
    {
      loadNo: 'LD-1001B',
      mode: '汽运',
      carpool: '同流向同交期合并',
      direction: '鲅鱼圈集港',
      date: '09-19',
      orders: 'SO-15018 + SO-15022',
      plate: '辽B·E2208',
      seq: '第 2 车，等前车吊完',
      wait: '26 分',
      vehicleLimit: '半挂 35t',
      goods: '热轧卷×7',
      mixOk: '同品类可混',
      weight: 30.1,
      fillRate: 86,
      status: '坪内等待',
    },
    {
      loadNo: 'LD-1002',
      mode: '汽运',
      carpool: '一票多车',
      direction: '营口港',
      date: '09-19',
      orders: 'SO-16022',
      plate: '辽B·C8812',
      seq: '第 1 车，盒板',
      wait: '0',
      vehicleLimit: '栏板 20t',
      goods: '中板×12',
      mixOk: '不可与卷混装',
      weight: 18.6,
      fillRate: 93,
      status: '装车中',
    },
    {
      loadNo: 'LD-1002B',
      mode: '汽运',
      carpool: '一票多车',
      direction: '营口港',
      date: '09-19',
      orders: 'SO-16022',
      plate: '辽B·F0911',
      seq: '第 2 车，等第 1 车驶离',
      wait: '18 分',
      vehicleLimit: '栏板 20t',
      goods: '中板×10',
      mixOk: '不可与卷混装',
      weight: 16.8,
      fillRate: 84,
      status: '坪内等待',
    },
    {
      loadNo: 'LD-1003',
      mode: '汽运',
      carpool: '客户指定不可拼',
      direction: '大连直送',
      date: '09-19',
      orders: 'SO-14007',
      plate: '辽B·D1190',
      seq: '独车',
      wait: '0',
      vehicleLimit: '半挂 35t',
      goods: '冷轧卷×6',
      mixOk: '不与热轧混',
      weight: 24.2,
      fillRate: 69,
      status: '已配载',
    },
  ],
  railLoads: [
    {
      loadNo: 'LD-R201',
      wagon: 'C70-8821',
      zone: '分区3 · 沈阳',
      orders: 'SO-13005 + SO-13008',
      goods: '线材 58.2t',
      mark: 70,
      fillRate: 83,
      mixOk: '同到站可拼',
      status: '已兑现，配载中',
      note: '车皮号已对照列车调度',
    },
    {
      loadNo: 'LD-R202',
      wagon: 'C70-8830',
      zone: '分区7',
      orders: 'SO-15018 余量',
      goods: '热轧卷 61t',
      mark: 70,
      fillRate: 87,
      mixOk: '不与冷卷混装',
      status: '已兑现，待装',
      note: '标重利用率按已兑现车皮计算',
    },
    {
      loadNo: 'LD-R203',
      wagon: '未兑现',
      zone: '分区1',
      orders: 'SO-17031',
      goods: '热轧卷 40t',
      mark: 70,
      fillRate: 0,
      mixOk: '—',
      status: '请车未兑现',
      note: '对不上车皮号，不算已配载',
    },
  ],

  cockpitMeta: {
    goal: '从原料进厂到成品外发的全链路指标与异常，支撑管理层梳理与决策。',
    sources: [
      { name: '产销一体化系统', owner: '鞍信公司' },
      { name: '制造执行系统（MES）', owner: '鞍钢自有系统' },
      { name: '销售管理系统', owner: '鞍信公司' },
      { name: '物流运输系统', owner: '鞍信公司' },
      { name: '德邻陆港汽运调度系统', owner: '德邻陆港' },
      { name: '码头系统', owner: '码头管理单位' },
      { name: '企业资源计划系统（ERP）', owner: '鞍钢自有系统' },
    ],
  },
  cockpitStats: [
    { label: '原料在途(港→厂)', value: 6, unit: '船/列', dim: '原料进厂' },
    { label: '成品库可发占比', value: 78, unit: '%', dim: '准发' },
    { label: '门口最长排队', value: 52, unit: '分钟', dim: '汽运调度' },
    { label: '装车坪最长等待', value: 58, unit: '分钟', dim: '装卸点' },
    { label: '汽运满载率', value: 82.1, unit: '%', dim: '配载' },
    { label: '铁运车皮兑现率', value: 82, unit: '%', dim: '铁运' },
    { label: '船等货泊位', value: 1, unit: '个', dim: '码头' },
    { label: '计划插单数(日)', value: 5, unit: '单', dim: '出厂计划' },
  ],
  alerts: [
    { level: '高', dim: '排队', content: '成品库东门回车占道，平均等待 52 分钟', time: '17:42' },
    { level: '高', dim: '装卸', content: '热轧装车坪等待最长 58 分钟，建议错峰预约', time: '17:35' },
    { level: '高', dim: '码头', content: '鲅鱼圈 4# 船等货，集港仅 10%', time: '17:20' },
    { level: '中', dim: '准发', content: '账面库存含积压不可发，SO-14007 可发仅一半', time: '17:05' },
    { level: '中', dim: '铁运', content: '车皮兑现率偏低，影响长江以北交期', time: '16:50' },
    { level: '低', dim: '配载', content: '沈阳方向满载率 69%，仍有拼车空间', time: '16:40' },
  ],
}
