import { defineStore } from 'pinia'
import { bizModuleState } from './bizModules'

export const useLogisticsStore = defineStore('logistics', {
  state: () => ({
    trackingStages: [
      {
        key: 1,
        name: '订货评审',
        sub: '订单号',
        keyNodes: ['订单评审'],
        process: {
          depts: [
            {
              name: '销售/经营部',
              org: '营销中心·客户服务',
              actions: ['客户订单受理 · 合同签订', '订单评审 · 交期承诺'],
            },
            {
              name: '生产部',
              org: '制造管理·运行室',
              actions: ['合同评审 · 工艺可行性', '产能预排 · 材料设计（材料号 / 化学成分 / 坯型设计）'],
            },
          ],
          docs: ['客户订单 / 订货合同', '订单评审单 · 材料申请单'],
        },
        sources: [
          { name: '销售管理系统', owner: '鞍信公司' },
          { name: '基础数据平台', owner: '鞍信公司' },
          { name: '产销一体化系统', owner: '鞍钢自有系统' },
        ],
        columns: [
          { prop: 'orderNo', label: '订单号/合同号', minWidth: 140 },
          { prop: 'customerCode', label: '客户编码', minWidth: 110 },
          { prop: 'address', label: '收货地址', minWidth: 140 },
          { prop: 'priority', label: '客户优先级', width: 100 },
          { prop: 'deliveryDate', label: '交货期', width: 110 },
          { prop: 'grade', label: '牌号/钢种', minWidth: 120 },
          { prop: 'spec', label: '规格尺寸', minWidth: 140 },
          { prop: 'ton', label: '订单重量(吨)', width: 120 },
          { prop: 'pieces', label: '件数', width: 80 },
          { prop: 'techReq', label: '技术协议/特殊要求', minWidth: 160 },
          { prop: 'status', label: '状态', width: 100 },
        ],
        list: [
          {
            orderNo: 'SO-20260917031',
            customerCode: 'C-YK-018',
            address: '营口某加工园区',
            priority: '高',
            deliveryDate: '09-25',
            grade: 'Q355B',
            spec: '1500×4.0',
            ton: 40,
            pieces: 12,
            techReq: '表面质量A级',
            status: '评审中',
            goods: '热轧卷板',
            customer: '营口某加工',
            currentStage: 1,
          },
          {
            orderNo: 'SO-20260915018',
            customerCode: 'C-DB-003',
            address: '沈阳浑南仓库',
            priority: '中',
            deliveryDate: '09-22',
            grade: 'Q235B',
            spec: '1250×3.0',
            ton: 28.6,
            pieces: 8,
            techReq: '按技术协议 T-018',
            status: '已通过',
            goods: '热轧卷板',
            customer: '东北某制造',
            currentStage: 1,
          },
          {
            orderNo: 'SO-20260914007',
            customerCode: 'C-DL-021',
            address: '大连保税区',
            priority: '中',
            deliveryDate: '09-23',
            grade: 'DC01',
            spec: '1000×0.8',
            ton: 24.2,
            pieces: 6,
            techReq: '冷轧表面无划伤',
            status: '已通过',
            goods: '冷轧卷板',
            customer: '大连某仓储',
            currentStage: 1,
          },
        ],
      },
      {
        key: 2,
        name: '计划排产',
        sub: '材料号 / 炉次号',
        keyNodes: ['材料设计', '炉次计划'],
        process: {
          depts: [
            {
              name: '生产部',
              org: '制造管理·运行室',
              actions: ['生产计划编制 · 炉次排产', '冶炼工艺标准下达'],
            },
          ],
          docs: ['生产计划单 · 炉次排产计划', '材料号 → 炉次号'],
        },
        sources: [
          { name: '产销一体化系统', owner: '鞍钢自有系统' },
          { name: '制造执行系统（MES）', owner: '鞍钢自有系统' },
          { name: '检化验系统（LIMS）', owner: '鞍钢自有系统' },
          { name: '计量系统', owner: '鞍钢自有系统' },
        ],
        columns: [
          { prop: 'materialNo', label: '材料号', minWidth: 120 },
          { prop: 'chemDesign', label: '化学成分设计', minWidth: 140 },
          { prop: 'processPath', label: '工艺路径', minWidth: 140 },
          { prop: 'billetDesign', label: '坯型设计/定尺', minWidth: 130 },
          { prop: 'heatNo', label: '炉次号', minWidth: 120 },
          { prop: 'slabNo', label: '板坯号', minWidth: 120 },
          { prop: 'unitWeight', label: '单重(吨)', width: 100 },
          { prop: 'orderNo', label: '关联订单', minWidth: 130 },
          { prop: 'status', label: '状态', width: 100 },
        ],
        list: [
          {
            materialNo: 'M-HR-79002',
            chemDesign: 'C0.16 / Mn1.45',
            processPath: '炼钢→连铸→热轧',
            billetDesign: '板坯 230×1500',
            heatNo: 'H-260918-02',
            slabNo: '待下达',
            unitWeight: 28,
            orderNo: 'SO-20260917031',
            status: '计划中',
            goods: '热轧卷板',
            customer: '营口某加工',
            spec: 'Q355B / 1500×4.0',
            ton: 40,
            currentStage: 2,
          },
          {
            materialNo: 'M-HR-77821',
            chemDesign: 'C0.14 / Mn0.85',
            processPath: '炼钢→连铸→热轧',
            billetDesign: '板坯 230×1250',
            heatNo: 'H-260916-03',
            slabNo: 'SL-260916-118',
            unitWeight: 26.5,
            orderNo: 'SO-20260915018',
            status: '已下发',
            goods: '热轧卷板',
            customer: '东北某制造',
            spec: 'Q235B / 1250×3.0',
            ton: 28.6,
            currentStage: 2,
          },
          {
            materialNo: 'M-PL-33108',
            chemDesign: 'EH36 船板成分',
            processPath: '炼钢→连铸→中板',
            billetDesign: '板坯 250×2000',
            heatNo: 'H-260917-01',
            slabNo: 'SL-260917-021',
            unitWeight: 32,
            orderNo: 'SO-20260916022',
            status: '执行中',
            goods: '中厚板坯',
            customer: '华东某船厂',
            spec: 'EH36 / 20mm',
            ton: 32,
            currentStage: 2,
          },
        ],
      },
      {
        key: 3,
        name: '炼钢连铸',
        sub: '板坯号',
        keyNodes: ['连铸板坯'],
        process: {
          depts: [
            {
              name: '制造部',
              org: '炼钢厂',
              actions: ['铁水预处理 → 转炉冶炼 → LF/RH 精炼 → 连铸（板坯 / 方坯）'],
            },
          ],
          docs: ['生产计划单 · 炉次排产计划', '材料号 → 炉次号 → 板坯号'],
        },
        sources: [
          { name: '制造执行系统（MES）', owner: '鞍钢自有系统' },
          { name: '检化验系统（LIMS）', owner: '鞍钢自有系统' },
          { name: '计量系统', owner: '鞍钢自有系统' },
        ],
        columns: [
          { prop: 'heatNo', label: '炉次号', minWidth: 120 },
          { prop: 'hotMetal', label: '铁水成分/温度', minWidth: 140 },
          { prop: 'steelChem', label: '钢水化学成分', minWidth: 160 },
          { prop: 'refineParam', label: '精炼参数', minWidth: 130 },
          { prop: 'castSpeed', label: '连铸拉速/冷却', minWidth: 130 },
          { prop: 'slabNo', label: '板坯号', minWidth: 120 },
          { prop: 'unitWeight', label: '单重(吨)', width: 100 },
          { prop: 'materialNo', label: '材料号', minWidth: 120 },
          { prop: 'status', label: '状态', width: 100 },
        ],
        list: [
          {
            heatNo: 'H-260917-01',
            hotMetal: 'P0.08 / S0.02 · 1380℃',
            steelChem: 'C0.15 Si0.25 Mn1.40',
            refineParam: 'LF 18min / RH 12min',
            castSpeed: '1.1m/min · 二冷区正常',
            slabNo: 'SL-260917-021',
            unitWeight: 32,
            materialNo: 'M-PL-33108',
            status: '浇铸中',
            goods: '中厚板坯',
            customer: '华东某船厂',
            spec: 'EH36 / 20mm',
            ton: 32,
            currentStage: 3,
          },
          {
            heatNo: 'H-260916-03',
            hotMetal: 'P0.07 / S0.018 · 1375℃',
            steelChem: 'C0.14 Si0.20 Mn0.80',
            refineParam: 'LF 15min',
            castSpeed: '1.2m/min · 定尺切割完成',
            slabNo: 'SL-260916-118',
            unitWeight: 26.5,
            materialNo: 'M-HR-77821',
            status: '已产出',
            goods: '热轧卷板',
            customer: '东北某制造',
            spec: 'Q235B / 1250×3.0',
            ton: 28.6,
            currentStage: 3,
          },
          {
            heatNo: 'H-260914-11',
            hotMetal: 'P0.06 / S0.015 · 1385℃',
            steelChem: 'C0.05 Si0.03 Mn0.25',
            refineParam: 'LF+RH',
            castSpeed: '1.15m/min',
            slabNo: 'SL-260914-086',
            unitWeight: 24,
            materialNo: 'M-CR-55210',
            status: '已产出',
            goods: '冷轧卷板',
            customer: '大连某仓储',
            spec: 'DC01 / 1000×0.8',
            ton: 24.2,
            currentStage: 3,
          },
        ],
      },
      {
        key: 4,
        name: '热轧冷轧',
        sub: '卷号',
        keyNodes: ['轧制卷取'],
        process: {
          depts: [
            {
              name: '生产部',
              org: '制造管理·运行室',
              actions: ['轧制计划编制', '轧制工艺卡下达（压下 / 温度制度）'],
            },
            {
              name: '制造部',
              org: '热轧 / 冷轧厂',
              actions: ['加热 → 粗轧 → 精轧 → 卷取', '冷轧 → 退火 → 平整 → 精整'],
            },
          ],
          docs: ['轧制计划 / 轧制工艺卡', '炉次号 → 板坯号 → 卷号'],
        },
        sources: [
          { name: '制造执行系统（MES）', owner: '鞍钢自有系统' },
          { name: '检化验系统（LIMS）', owner: '鞍钢自有系统' },
          { name: '基础数据平台', owner: '鞍信公司' },
        ],
        columns: [
          { prop: 'coilNo', label: '卷号', minWidth: 140 },
          { prop: 'subCoil', label: '子卷号', width: 100 },
          { prop: 'furnaceTemp', label: '加热炉温度/在炉时间', minWidth: 160 },
          { prop: 'rollParam', label: '轧制参数', minWidth: 150 },
          { prop: 'coilInfo', label: '卷重/内外径', minWidth: 130 },
          { prop: 'finishParam', label: '冷轧/退火/精整', minWidth: 140 },
          { prop: 'abnormal', label: '异常记录', minWidth: 120 },
          { prop: 'slabNo', label: '板坯号', minWidth: 120 },
          { prop: 'status', label: '状态', width: 100 },
        ],
        list: [
          {
            coilNo: 'C-HR-260917-052',
            subCoil: '—',
            furnaceTemp: '1230℃ / 186min',
            rollParam: '终轧 860℃ / 速度正常',
            coilInfo: '28.6t · Φ760/Φ1850',
            finishParam: '热轧直发',
            abnormal: '无',
            slabNo: 'SL-260916-118',
            status: '已卷取',
            goods: '热轧卷板',
            customer: '东北某制造',
            spec: 'Q235B / 1250×3.0',
            ton: 28.6,
            currentStage: 4,
          },
          {
            coilNo: 'C-CR-260916-033',
            subCoil: 'SC-01',
            furnaceTemp: '—',
            rollParam: '冷轧压下 72%',
            coilInfo: '24.2t · Φ610/Φ1650',
            finishParam: '退火+平整完成',
            abnormal: '无',
            slabNo: 'SL-260914-086',
            status: '已精整',
            goods: '冷轧卷板',
            customer: '大连某仓储',
            spec: 'DC01 / 1000×0.8',
            ton: 24.2,
            currentStage: 4,
          },
          {
            coilNo: 'C-WR-260915-019',
            subCoil: '—',
            furnaceTemp: '1180℃ / 150min',
            rollParam: '线材轧制正常',
            coilInfo: '31.5t',
            finishParam: '集卷完成',
            abnormal: '无',
            slabNo: 'BL-260913-044',
            status: '已完成',
            goods: '线材',
            customer: '沈阳某贸易',
            spec: 'HRB400E / Φ8',
            ton: 31.5,
            currentStage: 4,
          },
        ],
      },
      {
        key: 5,
        name: '质量入库',
        sub: '库位号',
        keyNodes: ['质量入库'],
        process: {
          depts: [
            {
              name: '制造部',
              org: '炼钢 / 热轧 / 冷轧厂',
              actions: ['质量检验 · 质量判定', '成品入库上架'],
            },
          ],
          docs: ['质量证明书 / 质保书', '卷号 → 库位号'],
        },
        sources: [
          { name: '质量管理系统', owner: '鞍钢自有系统' },
          { name: '企业资源计划系统（ERP）', owner: '鞍钢自有系统' },
        ],
        columns: [
          { prop: 'productNo', label: '成品编号', minWidth: 130 },
          { prop: 'goods', label: '品类', width: 100 },
          { prop: 'grade', label: '牌号', width: 100 },
          { prop: 'spec', label: '规格', minWidth: 120 },
          { prop: 'unitWeight', label: '单件重量', width: 100 },
          { prop: 'stackRule', label: '堆高/承重/可叠放', minWidth: 150 },
          { prop: 'binNo', label: '库区/库位', minWidth: 120 },
          { prop: 'coord', label: '三维坐标', minWidth: 110 },
          { prop: 'quality', label: '质量判定', width: 100 },
          { prop: 'status', label: '状态', width: 100 },
        ],
        list: [
          {
            productNo: 'FP-HR-052',
            goods: '热轧卷板',
            grade: 'Q235B',
            spec: '1250×3.0',
            unitWeight: 28.6,
            stackRule: '3层 / 90t / 可叠放',
            binNo: 'A区-12-03',
            coord: 'X12 Y03 Z1',
            quality: '合格',
            status: '在库待发',
            customer: '东北某制造',
            ton: 28.6,
            coilNo: 'C-HR-260917-052',
            orderNo: 'SO-20260915018',
            currentStage: 5,
          },
          {
            productNo: 'FP-CR-033',
            goods: '冷轧卷板',
            grade: 'DC01',
            spec: '1000×0.8',
            unitWeight: 24.2,
            stackRule: '2层 / 60t / 可叠放',
            binNo: 'B区-05-08',
            coord: 'X05 Y08 Z1',
            quality: '合格',
            status: '已出库',
            customer: '大连某仓储',
            ton: 24.2,
            coilNo: 'C-CR-260916-033',
            orderNo: 'SO-20260914007',
            currentStage: 5,
          },
          {
            productNo: 'FP-WR-019',
            goods: '线材',
            grade: 'HRB400E',
            spec: 'Φ8',
            unitWeight: 31.5,
            stackRule: '4层 / 80t / 可叠放',
            binNo: 'C区-02-11',
            coord: 'X02 Y11 Z2',
            quality: '合格',
            status: '已出库',
            customer: '沈阳某贸易',
            ton: 31.5,
            coilNo: 'C-WR-260915-019',
            orderNo: 'SO-20260913005',
            currentStage: 5,
          },
        ],
      },
      {
        key: 6,
        name: '装车发运',
        sub: '运单号',
        keyNodes: ['提货发运'],
        process: {
          depts: [
            {
              name: '销售/经营部',
              org: '营销中心·客户服务',
              actions: ['提货计划 · 装车配载', '发运出厂 · 送达签收'],
            },
          ],
          docs: ['装车配载单 · 派车单 · 准运单', '库位号 → 运单号'],
        },
        sources: [
          { name: '物流运输系统', owner: '鞍信公司' },
          { name: '德邻陆港汽运调度系统', owner: '德邻陆港' },
          { name: '企业资源计划系统（ERP）', owner: '鞍钢自有系统' },
        ],
        columns: [
          { prop: 'waybillNo', label: '运单号', minWidth: 120 },
          { prop: 'orderNo', label: '订单号', minWidth: 130 },
          { prop: 'ton', label: '总吨位', width: 90 },
          { prop: 'pickup', label: '提货地址', minWidth: 120 },
          { prop: 'arriveTime', label: '送达时间', width: 120 },
          { prop: 'plate', label: '车牌号', width: 110 },
          { prop: 'vehicleType', label: '车型/额定载重', minWidth: 130 },
          { prop: 'vehiclePos', label: '车辆位置', minWidth: 120 },
          { prop: 'loadResult', label: '装车实绩', minWidth: 110 },
          { prop: 'track', label: '在途/签收', minWidth: 120 },
          { prop: 'status', label: '状态', width: 100 },
        ],
        list: [
          {
            waybillNo: 'WB-26091702',
            orderNo: 'SO-20260914007',
            ton: 24.2,
            pickup: '冷轧成品库 B区',
            arriveTime: '09-18 20:30',
            plate: '辽B·D1190',
            vehicleType: '半挂 / 35t',
            vehiclePos: '沈大高速 K182',
            loadResult: '已装车 24.2t',
            track: '运输中',
            status: '运输中',
            goods: '冷轧卷板',
            customer: '大连某仓储',
            spec: 'DC01 / 1000×0.8',
            currentStage: 6,
          },
          {
            waybillNo: 'WB-26091608',
            orderNo: 'SO-20260913005',
            ton: 31.5,
            pickup: '线材库 C区',
            arriveTime: '09-17 11:20',
            plate: '辽B·A2036',
            vehicleType: '半挂 / 35t',
            vehiclePos: '沈阳库区',
            loadResult: '已装车 31.5t',
            track: '已签收',
            status: '已完成',
            goods: '线材',
            customer: '沈阳某贸易',
            spec: 'HRB400E / Φ8',
            currentStage: 6,
          },
          {
            waybillNo: 'WB-26091701',
            orderNo: 'SO-20260915018',
            ton: 28.6,
            pickup: '热轧成品库 A区',
            arriveTime: '待派车',
            plate: '待匹配',
            vehicleType: '半挂 / 35t',
            vehiclePos: '—',
            loadResult: '待装车',
            track: '未发运',
            status: '待发运',
            goods: '热轧卷板',
            customer: '东北某制造',
            spec: 'Q235B / 1250×3.0',
            currentStage: 6,
          },
        ],
      },
    ],
    ...bizModuleState,
  }),
})
